name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Optional: allows manual runs from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t francisroyce/flask-grade-predictor .

      - name: Push the Docker image to Docker Hub
        run: docker push francisroyce/flask-grade-predictor
